imagePullPolicy: IfNotPresent

# Values that are used for the dependency `cert-manager`
cert-manager:
  ingressShim:
    defaultIssuerKind: ClusterIssuer
    defaultIssuerName: letsencrypt-prod
  # installCRDs: true
  webhook:
    enabled: false
